lab_4/rent/account/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from .views import LoginView, CreateUserView, DashboardView, LogoutView, AuthUserView, \
    AuthUserProfileViewSet, UserProfileUpdateView

app_name = 'account'

urlpatterns = [
    path('auth/token/', obtain_auth_token, name='get_jwt'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth-user/', AuthUserView.as_view(), name='auth_user'),
    path('auth-user-profile/', AuthUserProfileViewSet.as_view({'get': 'list'}),
         name='auth_user_profile'),
    path('register/', CreateUserView.as_view(), name='register'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/update/', UserProfileUpdateView.as_view(), name='update')
]

lab_4/rent/drone/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import DroneViewSet, GetDronesView, GetdroneInfoView

app_name = 'drone'

urlpatterns = [
    path('', GetDronesView.as_view(), name='view_drones'),
    path('<int:pk>/info/', GetdroneInfoView.as_view(), name='get_drone_info'),

]

router = routers.DefaultRouter()
router.register('list', DroneViewSet)

urlpatterns += router.urls

lab_4/rent/rent_a_drone/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from account.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('drone/', include('drone.urls', namespace='drone')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:  # Use local only
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # For serving media files

lab_4/rent/templates/menu/home.html
<a href="{% url 'home' %}" class="navbar-item {% if request.path == '/' %} is-active {% endif %}"> Home </a>
<a href="{% url 'drone:view_drones' %}"  class="navbar-item {% if 'drone' in request.path %} is-active {% endif %}"> View drones </a>
<a href="{% url 'account:login' %}" class="navbar-item {% if 'login' in request.path %} is-active {% endif %}"> Login </a>
<a href="{% url 'account:register' %}" class="navbar-item {% if 'register' in request.path %} is-active {% endif %}"> Register </a>

lab_4/rent/templates/menu/user.html
<a href="#" class="navbar-item {% if 'dashboard' in request.path %} is-active {% endif %}" id="dashboard"> Dashboard </a>
<a href="{% url 'drone:view_drones' %}" class="navbar-item {% if 'drone' in request.path %} is-active {% endif %}"> View drones </a>
{% if user.is_authenticated %}
    <a href="{% url 'account:logout' %}" class="navbar-item"> Logout </a>
{% else %}
    <a href="#" class="navbar-item" id="logout"> Logout </a>
{% endif %}